'use strict';
const API_BASE=(window.BSS_API_BASE||'https://bhasha-shiksha-setu-backend.onrender.com').replace(/\/$/,'')+'/api';
const $=s=>document.querySelector(s); const messages=$('#messages');
function add(text,who='bot'){const d=document.createElement('div');d.className='bubble '+who;d.textContent=text;messages.appendChild(d);messages.scrollTop=messages.scrollHeight;return d}
async function api(path,opts={}){const r=await fetch(API_BASE+path,{...opts,headers:{'Content-Type':'application/json',...(opts.headers||{})}});let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.error||`Request failed (${r.status})`);return data}
async function boot(){try{const c=await api('/config');$('#health').textContent='● API connected';$('#health').classList.add('ok');$('#mode').textContent=c.ai_enabled?'Online • OpenAI AI enabled':'Demo mode • add API key for general AI';}catch(e){$('#health').textContent='● API offline';$('#mode').textContent='Backend connection failed';}}
async function send(q=null){const input=$('#question');q=q??input.value.trim();if(!q)return;const lang=$('#lang').value;add(q,'user');input.value='';const wait=add('Thinking…','bot');try{const d=await api('/chat',{method:'POST',body:JSON.stringify({message:q,language:lang,guest_id:'web-'+Date.now()})});wait.textContent=d.answer;wait.dataset.answer=d.answer;wait.addEventListener('click',()=>speak(d.answer,lang));}catch(e){wait.textContent='⚠️ '+e.message+'\n\nCheck that the backend URL is correct and CORS is enabled.'}}
function speak(text,lang){if(!('speechSynthesis' in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang={hi:'hi-IN',mr:'mr-IN',en:'en-IN',gu:'gu-IN',bn:'bn-IN',ta:'ta-IN',te:'te-IN'}[lang]||'hi-IN';window.speechSynthesis.speak(u)}
let rec=null;if('webkitSpeechRecognition' in window||'SpeechRecognition' in window){const R=window.SpeechRecognition||window.webkitSpeechRecognition;rec=new R();rec.interimResults=false;rec.continuous=false;rec.onstart=()=>$('#mic').textContent='⏺️';rec.onend=()=>$('#mic').textContent='🎙️';rec.onerror=()=>$('#mic').textContent='🎙️';rec.onresult=e=>{const t=e.results[0][0].transcript;$('#question').value=t;send(t)}}
$('#send').onclick=()=>send();$('#question').addEventListener('keydown',e=>{if(e.key==='Enter')send()});$('#mic').onclick=()=>{if(rec){rec.lang={hi:'hi-IN',mr:'mr-IN',en:'en-IN',gu:'gu-IN',bn:'bn-IN',ta:'ta-IN',te:'te-IN'}[$('#lang').value]||'hi-IN';rec.start()}else alert('Voice recognition is not supported by this browser.')};document.querySelectorAll('.chips button').forEach(b=>b.onclick=()=>send(b.dataset.q));$('#clear').onclick=()=>{messages.innerHTML='';add('Chat cleared. Ask me anything in your language.','bot')};
async function lessonAction(type){const text=$('#lessonText').textContent,lang=$('#lang').value,res=$('#lessonResult');res.style.display='block';res.textContent='Working…';try{const d=await api(type==='translate'?'/translate':'/explain',{method:'POST',body:JSON.stringify(type==='translate'?{text,target_language:lang}:{text,language:lang})});res.textContent=type==='translate'?d.translated_text:d.explanation}catch(e){res.textContent='⚠️ '+e.message}}
$('#translate').onclick=()=>lessonAction('translate');$('#explain').onclick=()=>lessonAction('explain');$('#speakLesson').onclick=()=>speak($('#lessonResult').textContent||$('#lessonText').textContent,$('#lang').value);boot();
